language: node_js
node_js:
  - "6.5.0"

# Other settings

install:
  - "npm install"
  - "npm install bower"
  - "bower install"

before_script:
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"

script: 
  - gulp test